language: java
env:
 global:
  - SONATYPE_USERNAME=vpro
   secure: "rDZyoBSlWVdo+5Po6AAxRPu0wSl8YYMgtXYtBqVOCqyeZYfTNgBwu91d4ZHrFRA2q74M6mk6JCg3EC2HSVD59p+6aAZCoPFopHq0q03s+b5f+8dPRHFkT123VQSNe/41d1rKEZsXdyP9V00LSE4/PjEJ1yPxxiI8QPwNAtsG3K5gdDMD4WUeuihybift+8pHG2AkhtH2g/GnyM56Xsx5MCkiAxHPD28QDc11cz+YXYGqS3jiYnZX7RMcaazZzHArf9ifmkKdjEjwVjU1Yj+PbMthXt2BcZfW+5RagZj9HHFDg4aduIr/5A402MnkxpNcLtJyXV2ORZBMvHXCGt5E/n2JHbkz5m/wSUw7AVP8rUvckfXpcRn+hCe5igA9cs/oCZwQ9j6qloQP+fqN616HO1LQiXtMuFq94Kp/my38eA2gAtvrKn03AyOGa22LBSr01+RxyjAY4hri4do8k2HYtE77/Uxff5v0KFzcHmvFKDUZ3OQ1DtjAk8EoxapKWa0TOZ74CTNKEpgzjzS7tT2OveKrSXTAvnVp7nIzVmUhjeJU+BxRsC2oXKw5e3k4ChM/IsEIxFwbyTgPB8xmtBWMkEDfdqcP6ysgy6xSm4mgtIodRQFlsfZlpxk66UBMsG1Qu8RvowTq9nuAR/1fR28GDhSYxLB81JS5XrmRwqGqJ7s="

jdk:
- oraclejdk8

sudo: false

script: mvn clean test install

after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
