language: java
env:
 global:
  - SONATYPE_USERNAME=mihxil
  - secure: "kq5iEDbH3otzXAZ3NOweyhy5MzAkIBmMr6kgk3UpfjaB39NEMftiZG7sH5v6FcEv2iGzKn5T118+CAg06UDWjSqI36F0j1uQbWofiSp05fqgPqN3sHUUtUGI4BCwUZpJKqispcPJjhs99zKedq/emkDFvbdKKGtRk30YyH3neyEzaM/E+FPjOyT0Sd7IHdnj6zeSkfVQP1T7LvcVsijLm9yI91fSA7WawwMSYVTBMhmZ11vkkrapJ+LnoTY5UHBipYhDq4dnvNaYd7Xq5mkLVKfRvkRthI6MI27Q9uYZu7f4g5W3QG26qX4XzUwNQ7bZgtBsvuMIvCp8U2bgTySABrALjyCSOfDFyPz89Cl0h3NKngdEX1mi6McXoy+JNKQgu7khQZD/Z71SOEwREh3sykIMcNeJJcDnTd/E2QKiCEBPsn9vuRP4mdsKc/QCam2L9xrNkpGPCsV0QajiNDuQot+ts1DU8BtIy/OVTorCLMhkeNB39zbaihudAFP+Kt9LgSACK4KZ0s5OPZLUfXFC6lROzXPwfUEscLBDvfL/I2ndyi+US7QJLoCJL4bhW1C7Cvftw/RQVmg2bBeud+DaiSyDRtwnDNB81LSjftLTsKbjyGUq55nGlwOWn3O2ylX6wfyXLVCS3PgbWaPmr1DA5cvA2jDgXBqUJjdikg9hukk="


jdk:
- oraclejdk8

sudo: false

script: mvn clean test install

after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
