language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: pKvdVT7TrX9kZQs28dQo2pnD8NEHgd9EPDA33wIy0Ecw1Zt6+x3XNHjmho+HbfL6GgspobPw4zWLZVNjMb6FQWM7K4iG71WaycjJNDs71yBYGVrh4WfQh3XpsmUwbg8zncnY5PS9YfG1h26hPxpwiVOvokj0qirxxqthHAkoZoWk44VdV+R5OMSFLc4mmuXzob7K2b8ihYihzl8oGLdi4efPjYWaHPr0HO6jfp12f8BCT0tP8thlrunvrV5EjDVJ/6dUgn6DZpkI0t/2nTOEtdmdN7uSq43zqnuJLKWVPkmlqvYWn5BBM2w+yggpGLcXOGaRIFeZXmOy49inbTw3FAOlc8csNRt7/kfibuljLcPBlO4xbpsdjyul9Jj/nJyV0In1oMxvds48zPSAjGt2key9XsRAjn3KmDe3+8lG1VEqBg9QTpj22FSz4+Iv2UOl9IbNrbSdt/UvdSStTtHw13X/tqP+7lBkRr43EHOLHo93cKgRRQP5LihOF4ANp2MTHUmq4uvtQG0N4cClZ33e59ZmXy2CLlIb7+gSrlNYS6L76HIOkkEG6NVYGKTHmZOvfOR3fkSoQv73u5i7d47GwS+BdICLoV5W/JZ84Ur4UsLKfDO45lFH4tyLxTTJWco1SB3eSBkHSvCdbkfeszBL0eqGHXwDjGRrSTyq0t1JQ+Y=
jdk:
- oraclejdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
